spring:
  profiles:
    active: prod
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        format_sql: true
        use_sql_comments: true
  jackson:
    time-zone: Asia/Seoul
  servlet:
    multipart:
      enabled: true # 파일 업로드 허용
      max-file-size: 200MB # 업로드 파일 최대 크기
      max-request-size: 1000MB # 요청 전체 최대 크기
      file-size-threshold: 10MB
  mvc:
    format:
      date-time: "yyyy-MM-dd'T'HH:mm:ss"
    pathmatch:
      matching-strategy: ant_path_matcher

chuseok22:
  api-change-log:
    enabled: true
    entries-to-show: 10
    date-format: "yyyy-MM-dd"
